#!/usr/bin/env bash
#
# Canopy installer — installs canopyd on macOS.
# Usage: curl -fsSL https://canopy.dev/install.sh | bash
#
set -euo pipefail

RELEASES_URL="https://releases.canopy.dev/latest"
INSTALL_DIR="/usr/local/bin"
BINARY_NAME="canopyd"
CONFIG_DIR="$HOME/.config/canopy"

# Colors for output.
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() { echo -e "  ${GREEN}✓${NC} $1"; }
warn() { echo -e "  ${YELLOW}!${NC} $1"; }
fail() { echo -e "  ${RED}✗${NC} $1" >&2; exit 1; }

# ─── Check prerequisites ───────────────────────────────────────────
[ "$(uname)" = "Darwin" ] || fail "canopyd only supports macOS"
command -v curl &>/dev/null || fail "curl is required"

# ─── Detect architecture ───────────────────────────────────────────
ARCH="$(uname -m)"
case "$ARCH" in
    arm64)  BINARY_SUFFIX="darwin-arm64" ;;
    x86_64) BINARY_SUFFIX="darwin-amd64" ;;
    *)      fail "Unsupported architecture: $ARCH" ;;
esac

echo ""
echo "  Installing canopyd ($BINARY_SUFFIX)..."
echo ""

# ─── Download binary ───────────────────────────────────────────────
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

BINARY_URL="$RELEASES_URL/$BINARY_NAME-$BINARY_SUFFIX"
CHECKSUM_URL="$RELEASES_URL/checksums.txt"

curl -fsSL -o "$TMPDIR/$BINARY_NAME" "$BINARY_URL" \
    || fail "Failed to download $BINARY_URL"

# ─── Verify checksum ──────────────────────────────────────────────
if curl -fsSL -o "$TMPDIR/checksums.txt" "$CHECKSUM_URL" 2>/dev/null; then
    EXPECTED=$(grep "$BINARY_NAME-$BINARY_SUFFIX" "$TMPDIR/checksums.txt" | awk '{print $1}')
    if [ -n "$EXPECTED" ]; then
        ACTUAL=$(shasum -a 256 "$TMPDIR/$BINARY_NAME" | awk '{print $1}')
        if [ "$EXPECTED" != "$ACTUAL" ]; then
            fail "Checksum mismatch. Expected: $EXPECTED Got: $ACTUAL"
        fi
        info "Checksum verified"
    else
        warn "Could not find checksum for $BINARY_SUFFIX (skipping verification)"
    fi
else
    warn "Could not download checksums (skipping verification)"
fi

# ─── Install binary ───────────────────────────────────────────────
chmod 755 "$TMPDIR/$BINARY_NAME"

if [ -w "$INSTALL_DIR" ]; then
    mv "$TMPDIR/$BINARY_NAME" "$INSTALL_DIR/$BINARY_NAME"
else
    sudo mv "$TMPDIR/$BINARY_NAME" "$INSTALL_DIR/$BINARY_NAME"
fi
info "canopyd installed to $INSTALL_DIR/$BINARY_NAME"

# ─── Create config directory ──────────────────────────────────────
mkdir -p "$CONFIG_DIR"/{sessions,parsers}
info "Config directory: $CONFIG_DIR"

# ─── Generate keys ────────────────────────────────────────────────
if [ ! -f "$CONFIG_DIR/identity.key" ]; then
    # Use canopyd itself to generate keys during first start.
    # For now, we just ensure the directory exists.
    # Keys are generated by the daemon on first run.
    info "Keys will be generated on first daemon start"
else
    info "Identity keys already exist"
fi

# ─── Write default config ────────────────────────────────────────
if [ ! -f "$CONFIG_DIR/config.json" ]; then
    cat > "$CONFIG_DIR/config.json" << 'CONFIGEOF'
{
  "listen_port": 19876,
  "wg_listen_port": 51820,
  "coord_url": "https://coord.canopy.dev",
  "capture_all_sessions": true,
  "capture_exclude_processes": ["ssh-agent", "gpg-agent"],
  "capture_exclude_env": {"CANOPY_DISABLE": "1"},
  "parsers_enabled": ["generic", "claude_code", "aider", "goose", "codex"],
  "shell_integration_markers": true,
  "retention_days": 30,
  "max_storage_gb": 10,
  "compress_after_hours": 24,
  "prevent_sleep_while_active": true,
  "auto_update": true,
  "file_access_root": null,
  "file_access_max_size_mb": 1,
  "max_paired_devices": 10
}
CONFIGEOF
    info "Default config written"
fi

# ─── Initialize devices.json ─────────────────────────────────────
if [ ! -f "$CONFIG_DIR/devices.json" ]; then
    echo '[]' > "$CONFIG_DIR/devices.json"
    chmod 600 "$CONFIG_DIR/devices.json"
fi

# ─── Inject shell hooks ──────────────────────────────────────────
inject_hook() {
    local rcfile="$1"
    local hook_code="$2"
    local integration_code="$3"

    # Create file if it doesn't exist.
    [ -f "$rcfile" ] || touch "$rcfile"

    # Remove existing hooks (idempotent).
    if grep -q "Canopy Hook" "$rcfile" 2>/dev/null; then
        # Use sed to remove the hook block.
        sed -i '' '/# --- Canopy Hook (do not edit) ---/,/# --- End Canopy Hook ---/d' "$rcfile"
    fi
    if grep -q "Canopy Shell Integration" "$rcfile" 2>/dev/null; then
        sed -i '' '/# --- Canopy Shell Integration (do not edit) ---/,/# --- End Canopy Shell Integration ---/d' "$rcfile"
    fi

    # Append hooks.
    printf '\n%s\n\n%s\n' "$hook_code" "$integration_code" >> "$rcfile"
}

# Zsh hook.
ZSH_HOOK='# --- Canopy Hook (do not edit) ---
if [ -z "$CANOPY_SESSION_ID" ] && command -v canopyd &>/dev/null && canopyd daemon ping &>/dev/null; then
  export CANOPY_SESSION_ID=$(uuidgen)
  exec canopyd attach --session-id "$CANOPY_SESSION_ID" -- "$SHELL" -l
fi
# --- End Canopy Hook ---'

ZSH_INTEGRATION='# --- Canopy Shell Integration (do not edit) ---
__canopy_precmd() {
  local exit_code=$?
  printf '"'"'\e]133;D;%s\a'"'"' "$exit_code"
  printf '"'"'\e]133;A\a'"'"'
}
__canopy_preexec() {
  printf '"'"'\e]133;C\a'"'"'
}
autoload -Uz add-zsh-hook 2>/dev/null && {
  add-zsh-hook precmd __canopy_precmd
  add-zsh-hook preexec __canopy_preexec
}
# --- End Canopy Shell Integration ---'

BASH_HOOK='# --- Canopy Hook (do not edit) ---
if [ -z "$CANOPY_SESSION_ID" ] && command -v canopyd &>/dev/null && canopyd daemon ping &>/dev/null; then
  export CANOPY_SESSION_ID=$(uuidgen)
  exec canopyd attach --session-id "$CANOPY_SESSION_ID" -- "$SHELL" -l
fi
# --- End Canopy Hook ---'

BASH_INTEGRATION='# --- Canopy Shell Integration (do not edit) ---
__canopy_precmd() {
  local exit_code=$?
  printf '"'"'\e]133;D;%s\a'"'"' "$exit_code"
  printf '"'"'\e]133;A\a'"'"'
}
__canopy_preexec() {
  printf '"'"'\e]133;C\a'"'"'
}
PROMPT_COMMAND="__canopy_precmd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
trap '"'"'__canopy_preexec'"'"' DEBUG
# --- End Canopy Shell Integration ---'

FISH_HOOK='# --- Canopy Hook (do not edit) ---
if not set -q CANOPY_SESSION_ID; and command -v canopyd &>/dev/null; and canopyd daemon ping &>/dev/null
  set -gx CANOPY_SESSION_ID (uuidgen)
  exec canopyd attach --session-id $CANOPY_SESSION_ID -- $SHELL -l
end
# --- End Canopy Hook ---'

FISH_INTEGRATION='# --- Canopy Shell Integration (do not edit) ---
function __canopy_postexec --on-event fish_postexec
  printf '"'"'\e]133;D;%s\a'"'"' $status
  printf '"'"'\e]133;A\a'"'"'
end
function __canopy_preexec --on-event fish_preexec
  printf '"'"'\e]133;C\a'"'"'
end
# --- End Canopy Shell Integration ---'

# Detect and inject for each shell.
SHELLS_HOOKED=""

if [ -f "$HOME/.zshrc" ] || [ "$(basename "$SHELL")" = "zsh" ]; then
    inject_hook "$HOME/.zshrc" "$ZSH_HOOK" "$ZSH_INTEGRATION"
    SHELLS_HOOKED="$SHELLS_HOOKED ~/.zshrc"
fi

if [ -f "$HOME/.bashrc" ]; then
    inject_hook "$HOME/.bashrc" "$BASH_HOOK" "$BASH_INTEGRATION"
    SHELLS_HOOKED="$SHELLS_HOOKED ~/.bashrc"
fi

if command -v fish &>/dev/null; then
    FISH_CONFIG="$HOME/.config/fish/config.fish"
    mkdir -p "$(dirname "$FISH_CONFIG")"
    inject_hook "$FISH_CONFIG" "$FISH_HOOK" "$FISH_INTEGRATION"
    SHELLS_HOOKED="$SHELLS_HOOKED config.fish"
fi

if [ -n "$SHELLS_HOOKED" ]; then
    info "Shell hooks added to$SHELLS_HOOKED"
else
    warn "No shell rc files found to hook"
fi

# ─── Install launchd plist ────────────────────────────────────────
PLIST_DIR="$HOME/Library/LaunchAgents"
PLIST_PATH="$PLIST_DIR/dev.canopy.daemon.plist"
mkdir -p "$PLIST_DIR"

cat > "$PLIST_PATH" << PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>dev.canopy.daemon</string>
  <key>ProgramArguments</key>
  <array>
    <string>$INSTALL_DIR/$BINARY_NAME</string>
    <string>daemon</string>
    <string>start</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>StandardOutPath</key>
  <string>/tmp/canopyd.stdout.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/canopyd.stderr.log</string>
  <key>ProcessType</key>
  <string>Background</string>
  <key>LowPriorityIO</key>
  <true/>
</dict>
</plist>
PLISTEOF

# Load the daemon.
launchctl load "$PLIST_PATH" 2>/dev/null || true
info "Daemon started"

# ─── Wait for daemon to come up and get device ID ────────────────
DEVICE_ID=""
for i in $(seq 1 10); do
    if "$INSTALL_DIR/$BINARY_NAME" daemon ping &>/dev/null; then
        # Read device ID from identity public key.
        if [ -f "$CONFIG_DIR/identity.pub" ]; then
            DEVICE_ID=$(shasum -a 256 "$CONFIG_DIR/identity.pub" | awk '{print substr($1,1,8)}')
        fi
        break
    fi
    sleep 0.5
done

HOSTNAME="$(hostname -s)"

# ─── Print summary ───────────────────────────────────────────────
echo ""
info "canopyd installed to $INSTALL_DIR/$BINARY_NAME"
info "Shell hooks added to$SHELLS_HOOKED"
info "Daemon started"
if [ -n "$DEVICE_ID" ]; then
    info "Device ID: $DEVICE_ID ($HOSTNAME)"
fi
echo ""
echo "  To pair your iPhone:"
echo "    canopyd pair"
echo ""
echo "  Open a new terminal tab to start capturing sessions."
echo ""
